WEB_DEV/WEB_DEV/Controllers/MagicButtonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB_DEV.Controllers
{
    public class MagicButtonController : Controller
    {
        //
        // GET: /MagicButton/

        public ActionResult MagicButton()
        {
            
            return View();
        }  
         
        
        
          
}
}

WEB_DEV/WEB_DEV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title — приложение ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("ваша эмблема здесь", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                            <li>@Html.ActionLink("О программе", "About", "Home")</li>
                            <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Magic Button", "MagicButton", "MagicButton") </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year — приложение ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>